[build]
  publish = "frontend"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/engineer"
  to = "/engineer.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/portal.html"
  status = 200
